---
title: "Clustering for Zeisel data"
author: "K4"
date: "06/28/2023"
output:
  html_notebook
---


```{r, results=FALSE, echo=FALSE, message=FALSE, warning=FALSE}
# Markdown parameters
set_echo = FALSE
set_eval = FALSE
```

```{r, results=FALSE, echo=FALSE, message=FALSE, warning=FALSE}
# Function to set markdown text color
colorize <- function(x, color) {
  if (knitr::is_latex_output()) {
    sprintf("\\textcolor{%s}{%s}", color, x)
  } else if (knitr::is_html_output()) {
    sprintf("<span style='color: %s;'>%s</span>", color,
      x)
  } else x
}
```


```{r, include=FALSE}
# Set height of chunk output
options(width = 60)
local({
  hook_output <- knitr::knit_hooks$get('output')
  knitr::knit_hooks$set(output = function(x, options) {
    if (!is.null(options$max.height)) options$attr.output <- c(
      options$attr.output,
      sprintf('style="max-height: %s;"', options$max.height)
    )
    hook_output(x, options)
  })
})
```

```{r, results = FALSE, echo=set_echo, message=FALSE, warning=FALSE}
# Load packages
library(dplyr)
library(Seurat)
library(patchwork)
library(ggplot2)
library(cowplot)
library(rmarkdown)
library(readr)
```

<!-- Information of Used Library -->
### `r colorize('Information of Used R Libraries', 'blue')` 

The following R libraries were used to process the data and produce this report.




```{r, echo=FALSE}
# Useful string constant
suffix <- "Seurat"
sampleName <- "Zeisel"
rawDataDir <- "scGND/data/Zeisel/outputs/"
projectName <- "Zeisel"

# Seurat parameters
variable.features <- 2000
nPCs <- 50
```


```{r, eval = set_eval, echo=FALSE}
# Load data
raw.data <- Read10X(data.dir = rawDataDir,gene.column = 1, cell.column = 2, unique.features = TRUE, strip.suffix = FALSE)
data <- CreateSeuratObject(counts = raw.data, project = projectName,  min.cells = 0, min.features = 0)#, min.cells = seuratQCMinCells, min.features = seuratQCMinGenes,)
data$group <- data@meta.data$orig.ident
# Save raw data
saveRDS(data, file = paste("data_raw.RDS") )
```


```{r,results='asis', echo=FALSE, message=FALSE, warning=FALSE}
countsBySample <- data.frame(unclass(table(data@meta.data$orig.ident)))
paged_table(countsBySample)
```



```{r, echo=FALSE}
# Load raw data
data <- readRDS("data_raw.RDS")
```



```{r, eval = set_eval, echo=FALSE}
data <- NormalizeData(data, normalization.method = "LogNormalize", scale.factor = 10000)
data <- FindVariableFeatures(data, selection.method = "vst", nfeatures = 2000)
data <- ScaleData(data, verbose = FALSE)

# dimension reduction
data <- RunPCA(data, npcs = 50, verbose = FALSE)
data <- RunUMAP(data, reduction = "pca", dims = 1:50)

# Save raw data
saveRDS(data, file = paste("data_umap.RDS") )
```

```{r, echo=FALSE}
# Load raw data
data <- readRDS("data_umap.RDS")
```



```{r, eval = set_eval, echo=FALSE}
# clustering
data <- FindNeighbors(data)
data <- FindClusters(data, resolution = 0.08)
```


```{r, echo=FALSE, message=FALSE, warning=FALSE}
DimPlot(data, reduction = "umap") + ggtitle('Groups')
```



```{r, echo=FALSE, message=FALSE, warning=FALSE}
# Save cluster labels as CSV
seurat_cluster = as.numeric(as.factor(data@meta.data$seurat_clusters))
write.table(seurat_cluster,file='seurat_cluster_label.csv',col.names=FALSE, row.names = FALSE)
write.table(data@reductions$umap@cell.embeddings,file='seurat_umap.csv',col.names=FALSE, row.names = FALSE)

```


